/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2002 from the
 * contents of vxs.xs. Do not edit this file, edit vxs.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "vxs.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#define NEED_sv_2pv_nolen_GLOBAL
#include "ppport.h"
#include "vutil.h"

/* --------------------------------------------------
 * $Revision: 2.5 $
 * --------------------------------------------------*/

typedef     SV *version_vxs;

#line 24 "vxs.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

#line 67 "vxs.c"

XS(XS_version__vxs_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_version__vxs_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    dXSI32;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 44 "vxs.xs"
{
    SV *vs = ST(1);
    SV *rv;
    const char * classname = "";
    PERL_UNUSED_ARG(ix);

    /* Just in case this is something like a tied hash */
    SvGETMAGIC(vs);

    if (items > 3 || items == 0)
        Perl_croak(aTHX_ "Usage: version::new(class, version)");

    if ( items == 1 || ! SvOK(vs) ) { /* no param or explicit undef */
        /* create empty object */
        vs = sv_newmortal();
        sv_setpvs(vs,"undef");
    }
    else if (items == 3 ) {
        vs = sv_newmortal();
        sv_setpvf(vs,"v%s",SvPV_nolen_const(ST(2)));
    }
    classname =
	sv_isobject(ST(0)) /* get the class if called as an object method */
	    ? HvNAME_get(SvSTASH(SvRV(ST(0))))
	    : (char *)SvPV_nolen(ST(0));

    rv = NEW_VERSION(vs);
    if ( strcmp(classname,"version::vxs") != 0 ) /* inherited new() */
#if PERL_VERSION == 5
        sv_bless(rv, gv_stashpv((char *)classname, GV_ADD));
#else
        sv_bless(rv, gv_stashpv(classname, GV_ADD));
#endif

    mPUSHs(rv);
}
#line 119 "vxs.c"
	PUTBACK;
	return;
    }
}


XS(XS_version__vxs_stringify); /* prototype to pass -Wmissing-prototypes */
XS(XS_version__vxs_stringify)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "lobj, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	version_vxs	lobj;

        if (ISA_CLASS_OBJ(ST(0), "version")) {
	    lobj = SvRV(ST(0));
        }
        else
            Perl_croak(aTHX_ "lobj is not of type version::vxs");
#line 85 "vxs.xs"
{
    mPUSHs(VSTRINGIFY(lobj));
}
#line 150 "vxs.c"
	PUTBACK;
	return;
    }
}


XS(XS_version__vxs_numify); /* prototype to pass -Wmissing-prototypes */
XS(XS_version__vxs_numify)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "lobj, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	version_vxs	lobj;

        if (ISA_CLASS_OBJ(ST(0), "version")) {
	    lobj = SvRV(ST(0));
        }
        else
            Perl_croak(aTHX_ "lobj is not of type version::vxs");
#line 93 "vxs.xs"
{
    mPUSHs(VNUMIFY(lobj));
}
#line 181 "vxs.c"
	PUTBACK;
	return;
    }
}


XS(XS_version__vxs_normal); /* prototype to pass -Wmissing-prototypes */
XS(XS_version__vxs_normal)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "ver");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	ver = ST(0);
#line 101 "vxs.xs"
{
    mPUSHs(VNORMAL(ver));
}
#line 206 "vxs.c"
	PUTBACK;
	return;
    }
}


XS(XS_version__vxs_VCMP); /* prototype to pass -Wmissing-prototypes */
XS(XS_version__vxs_VCMP)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "lobj, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	version_vxs	lobj;

        if (ISA_CLASS_OBJ(ST(0), "version")) {
	    lobj = SvRV(ST(0));
        }
        else
            Perl_croak(aTHX_ "lobj is not of type version::vxs");
#line 109 "vxs.xs"
{
    SV *rs;
    SV *rvs;
    SV *robj = ST(1);
    const IV  swap = (IV)SvIV(ST(2));

    if ( ! ISA_CLASS_OBJ(robj, "version::vxs") )
    {
        robj = NEW_VERSION(SvOK(robj) ? robj : newSVpvs_flags("undef", SVs_TEMP));
        sv_2mortal(robj);
    }
    rvs = SvRV(robj);

    if ( swap )
    {
        rs = newSViv(VCMP(rvs,lobj));
    }
    else
    {
        rs = newSViv(VCMP(lobj,rvs));
    }

    mPUSHs(rs);
}
#line 258 "vxs.c"
	PUTBACK;
	return;
    }
}


XS(XS_version__vxs_boolean); /* prototype to pass -Wmissing-prototypes */
XS(XS_version__vxs_boolean)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "lobj, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	version_vxs	lobj;

        if (ISA_CLASS_OBJ(ST(0), "version")) {
	    lobj = SvRV(ST(0));
        }
        else
            Perl_croak(aTHX_ "lobj is not of type version::vxs");
#line 138 "vxs.xs"
{
    SV * const rs =
    	newSViv( VCMP(lobj,
		      sv_2mortal(NEW_VERSION(
		      		 sv_2mortal(newSVpvs("0"))
				))
		     )
	       );
    mPUSHs(rs);
}
#line 296 "vxs.c"
	PUTBACK;
	return;
    }
}


XS(XS_version__vxs_noop); /* prototype to pass -Wmissing-prototypes */
XS(XS_version__vxs_noop)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "lobj, ...");
    {
	version_vxs	lobj;

        if (ISA_CLASS_OBJ(ST(0), "version")) {
	    lobj = SvRV(ST(0));
        }
        else
            Perl_croak(aTHX_ "lobj is not of type version::vxs");
#line 153 "vxs.xs"
{
    Perl_croak(aTHX_ "operation not supported with version object");
}
#line 325 "vxs.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_version__vxs_is_alpha); /* prototype to pass -Wmissing-prototypes */
XS(XS_version__vxs_is_alpha)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "lobj");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	version_vxs	lobj;

        if (ISA_CLASS_OBJ(ST(0), "version")) {
	    lobj = SvRV(ST(0));
        }
        else
            Perl_croak(aTHX_ "lobj is not of type version::vxs");
#line 161 "vxs.xs"
{
    if ( hv_exists(MUTABLE_HV(lobj), "alpha", 5 ) )
        XSRETURN_YES;
    else
        XSRETURN_NO;
}
#line 358 "vxs.c"
	PUTBACK;
	return;
    }
}


XS(XS_version__vxs_qv); /* prototype to pass -Wmissing-prototypes */
XS(XS_version__vxs_qv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    dXSI32;
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 173 "vxs.xs"
{
    SV *ver = ST(0);
    SV * rv;
    const char * classname = "";
    PERL_UNUSED_ARG(ix);

    if ( items == 2 ) {
	SvGETMAGIC(ST(1));
	if ( SvOK(ST(1)) ) {
	    /* getting called as object or class method */
	    ver = ST(1);
	}
	else {
	    Perl_croak(aTHX_ "Invalid version format (version required)");
	}
    }
#ifdef SvVOK
    if ( !SvVOK(ver) ) { /* not already a v-string */
#endif
        rv = sv_newmortal();
        sv_setsv(rv,ver); /* make a duplicate */
        UPG_VERSION(rv, TRUE);
#ifdef SvVOK
    }
    else
    {
        rv = sv_2mortal(NEW_VERSION(ver));
    }
#endif
    classname =
	sv_isobject(ST(0)) /* get the class if called as an object method */
	    ? HvNAME_get(SvSTASH(SvRV(ST(0))))
	    : (char *)SvPV_nolen(ST(0));

    if ( items == 2 && strcmp(classname,"version") ) {
        /* inherited new() */
#if PERL_VERSION == 5
        sv_bless(rv, gv_stashpv((char *)classname, GV_ADD));
#else
        sv_bless(rv, gv_stashpv(classname, GV_ADD));
#endif
    }
    PUSHs(rv);
}
#line 423 "vxs.c"
	PUTBACK;
	return;
    }
}


XS(XS_version__vxs_is_qv); /* prototype to pass -Wmissing-prototypes */
XS(XS_version__vxs_is_qv)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "lobj");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	version_vxs	lobj;

        if (ISA_CLASS_OBJ(ST(0), "version")) {
	    lobj = SvRV(ST(0));
        }
        else
            Perl_croak(aTHX_ "lobj is not of type version::vxs");
#line 222 "vxs.xs"
{
    if ( hv_exists(MUTABLE_HV(lobj), "qv", 2 ) )
        XSRETURN_YES;
    else
        XSRETURN_NO;
}
#line 457 "vxs.c"
	PUTBACK;
	return;
    }
}


XS(XS_version__vxs__VERSION); /* prototype to pass -Wmissing-prototypes */
XS(XS_version__vxs__VERSION)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "sv, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	sv = ST(0);
#line 233 "vxs.xs"
{
    HV *pkg;
    GV **gvp;
    GV *gv;
    SV *ret;
    const char *undef;

    if (SvROK(sv)) {
        sv = (SV*)SvRV(sv);
        if (!SvOBJECT(sv))
            Perl_croak(aTHX_ "Cannot find version of an unblessed reference");
        pkg = SvSTASH(sv);
    }
    else {
        pkg = gv_stashsv(sv, FALSE);
    }

    gvp = pkg ? (GV**)hv_fetchs(pkg,"VERSION",FALSE) : Null(GV**);

    if (gvp && isGV(gv = *gvp) && (sv = GvSV(gv)) && SvOK(sv)) {
        sv = sv_mortalcopy(sv);
	if ( ! ISA_CLASS_OBJ(sv, "version::vxs"))
	    UPG_VERSION(sv, FALSE);
        undef = NULL;
    }
    else {
        sv = ret = &PL_sv_undef;
        undef = "(undef)";
    }

    if (items > 1) {
        SV *req = ST(1);

        if (undef) {
             if (pkg) {
                const char * const name = HvNAME_get(pkg);
#if PERL_VERSION == 5
                Perl_croak(aTHX_ "%s version %s required--this is only version ",
                            name, SvPVx_nolen_const(req));
#else
                Perl_croak(aTHX_ "%s does not define $%s::VERSION--version check failed",
                            name, name);
#endif
             }
             else {
#if PERL_VERSION >= 8
                 Perl_croak(aTHX_ "%s defines neither package nor VERSION--version check failed",
                            SvPVx_nolen_const(ST(0)) );
#else
                 Perl_croak(aTHX_ "%s does not define $%s::VERSION--version check failed",
                            SvPVx_nolen_const(ST(0)),
                            SvPVx_nolen_const(ST(0)) );
#endif
             }
        }

        if ( ! ISA_CLASS_OBJ(req, "version")) {
            /* req may very well be R/O, so create a new object */
            req = sv_2mortal( NEW_VERSION(req) );
        }

        if ( VCMP( req, sv ) > 0 ) {
            if ( hv_exists(MUTABLE_HV(SvRV(req)), "qv", 2 ) ) {
                req = VNORMAL(req);
                sv  = VNORMAL(sv);
            }
            else {
                req = VSTRINGIFY(req);
                sv  = VSTRINGIFY(sv);
            }
            Perl_croak(aTHX_ "%s version %"SVf" required--"
                "this is only version %"SVf"", HvNAME_get(pkg),
                SVfARG(sv_2mortal(req)),
                SVfARG(sv_2mortal(sv)));
        }
    }
    ST(0) = ret;

    /* if the package's $VERSION is not undef, it is upgraded to be a version object */
    if (ISA_CLASS_OBJ(sv, "version")) {
	ST(0) = sv_2mortal(VSTRINGIFY(sv));
    } else {
	ST(0) = sv;
    }

    XSRETURN(1);
}
#line 566 "vxs.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_version__vxs); /* prototype to pass -Wmissing-prototypes */
XS(boot_version__vxs)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    const char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    {
        CV * cv ;

        cv = newXS("version::vxs::new", XS_version__vxs_new, file);
        XSANY.any_i32 = 0 ;
        cv = newXS("version::vxs::parse", XS_version__vxs_new, file);
        XSANY.any_i32 = 1 ;
        newXS("version::vxs::stringify", XS_version__vxs_stringify, file);
        newXS("version::vxs::numify", XS_version__vxs_numify, file);
        newXS("version::vxs::normal", XS_version__vxs_normal, file);
        newXS("version::vxs::VCMP", XS_version__vxs_VCMP, file);
        newXS("version::vxs::boolean", XS_version__vxs_boolean, file);
        newXS("version::vxs::noop", XS_version__vxs_noop, file);
        newXS("version::vxs::is_alpha", XS_version__vxs_is_alpha, file);
        cv = newXS("version::vxs::qv", XS_version__vxs_qv, file);
        XSANY.any_i32 = 0 ;
        cv = newXS("version::vxs::declare", XS_version__vxs_qv, file);
        XSANY.any_i32 = 1 ;
        newXS("version::vxs::is_qv", XS_version__vxs_is_qv, file);
        newXS("version::vxs::_VERSION", XS_version__vxs__VERSION, file);
    }

    /* Initialisation Section */

#line 20 "vxs.xs"
        /* register the overloading (type 'A') magic */
        PL_amagic_generation++;
        newXS("version::vxs::()", XS_version__vxs_noop, file);
        newXS("version::vxs::(\"\"", XS_version__vxs_stringify, file);
        newXS("version::vxs::(0+", XS_version__vxs_numify, file);
        newXS("version::vxs::(cmp", XS_version__vxs_VCMP, file);
        newXS("version::vxs::(<=>", XS_version__vxs_VCMP, file);
        newXS("version::vxs::(bool", XS_version__vxs_boolean, file);
        newXS("version::vxs::(+", XS_version__vxs_noop, file);
        newXS("version::vxs::(-", XS_version__vxs_noop, file);
        newXS("version::vxs::(*", XS_version__vxs_noop, file);
        newXS("version::vxs::(/", XS_version__vxs_noop, file);
        newXS("version::vxs::(+=", XS_version__vxs_noop, file);
        newXS("version::vxs::(-=", XS_version__vxs_noop, file);
        newXS("version::vxs::(*=", XS_version__vxs_noop, file);
        newXS("version::vxs::(/=", XS_version__vxs_noop, file);
        newXS("version::vxs::(abs", XS_version__vxs_noop, file);
        newXS("version::vxs::nomethod", XS_version__vxs_noop, file);

#line 631 "vxs.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

