use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006001
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
distmeta
dir
mailto
subkey
subkeys
David
Golden
dagolden
Ricardo
Signes
rjbs
and
Ansgar
Burchardt
ansgar
Avar
Arnfjord
Bjarmason
avar
Christopher
Madsen
cjm
Cory
Watson
gphat
Damyan
Ivanov
dam
Eric
Wilhelm
ewilhelm
Gregor
Hermann
gregoa
Karen
Etheridge
ether
Ken
Williams
kwilliams
Kenichi
Ishigaki
ishigaki
Lars
Dieckow
daxim
Leon
Timmermans
leont
Mark
Fowler
markf
Michael
Schwern
mschwern
Olaf
Alders
olaf
Olivier
Mengué
dolmen
Randy
Sims
randys
lib
CPAN
Meta
Feature
Validator
Converter
History
Spec
Prereqs
