---
abstract: 'Read and write a subset of YAML for CPAN Meta files'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Spec: 0
  File::Spec::Functions: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.94
  strict: 0
  vars: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Meta-YAML
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  CPAN::Meta::YAML:
    file: lib/CPAN/Meta/YAML.pm
    version: 0.010
requires:
  Carp: 0
  Exporter: 0
  Scalar::Util: 0
  perl: 5.006
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/CPAN-Meta-YAML/issues
  homepage: https://github.com/dagolden/CPAN-Meta-YAML
  repository: https://github.com/dagolden/CPAN-Meta-YAML.git
version: 0.010
x_authority: cpan:DAGOLDEN
