---
abstract: 'Structured version objects'
author:
  - 'John Peacock <jpeacock@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: version
no_index:
  directory:
    - t
    - inc
requires:
  File::Temp: 0.13
  Test::More: 0.45
  parent: 0.221
version: 0.9904
